<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Phosphor</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <LegacyCorruptedStateExceptionsPolicy>true</LegacyCorruptedStateExceptionsPolicy>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="default_thumb.png" />
    <None Remove="splash.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.7" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.5.1" />
    <PackageReference Include="Vortice.Direct3D9" Version="3.8.3" />
    <PackageReference Include="YoutubeExplode" Version="6.5.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="default_thumb.png" />
    <Resource Include="splash.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="default_settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="emoji_keywords.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="categories.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\dependencies\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>ffmpeg.exe</Link>
    </None>
    <None Include="..\dependencies\projectM\projectM-4.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>projectM-4.dll</Link>
    </None>
    <None Include="..\dependencies\projectM\projectM-4-playlist.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>projectM-4-playlist.dll</Link>
    </None>
    <None Include="..\dependencies\projectM\glew32.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>glew32.dll</Link>
    </None>
    <Content Include="..\dependencies\projectM\textures\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>presets\textures\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>


  </Project>
